### ISSUE TITLE
It is not possible to overwrite aws_cw_config_template_path for windows

### ISSUE THREAD

**Issue by nuclon** [riponbanik/ansible-role-aws-cloudwatch-agent#1]
The reason is the presence of the variable in role vars which have higher priority than playbook variables.

**Comment by deekayen** [comment]
It is possible, but the example in the readme could use a modification to add `{{ playbook_dir }}` if that's the recommended template location for overrides.

```
- hosts: all

  roles:
    - role: riponbanik.aws-cloudwatch-agent
      vars:
        aws_cw_config_template_path: "{{ playbook_dir }}/templates/agent-config.json.j2"


```
